-- MySQL Script generated by MySQL Workbench
-- Thu Sep 18 21:22:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exam_session
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exam_session
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exam_session` DEFAULT CHARACTER SET utf8 ;
USE `exam_session` ;

-- -----------------------------------------------------
-- Table `exam_session`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exam_session`.`student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NULL,
  `birthdate` DATE NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exam_session`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exam_session`.`teacher` (
  `teacher_id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NULL,
  PRIMARY KEY (`teacher_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exam_session`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exam_session`.`subject` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `term` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  PRIMARY KEY (`subject_id`),
  INDEX `fk_subject_teacher_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_subject_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `exam_session`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exam_session`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exam_session`.`grade` (
  `student_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `grade` INT NOT NULL,
  INDEX `fk_grade_subject_idx` (`subject_id` ASC) VISIBLE,
  INDEX `fk_grade_student_idx` (`student_id` ASC) VISIBLE,
  PRIMARY KEY (`student_id`, `subject_id`),
  CONSTRAINT `fk_grade_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `exam_session`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grade_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `exam_session`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
